name: cropa
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - ca-certificates=2023.7.22
  - comm=0.1.4
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - ipykernel=6.25.2
  - ipython=8.15.0
  - jedi=0.19.0
  - jupyter_client=7.3.4
  - jupyter_core=5.3.1
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - openssl=3.0.10
  - packaging=23.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.16.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=25.1.0
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.10.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - wcwidth=0.2.6
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - bert-score==0.3.13
      - braceexpand==0.1.7
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - click==8.1.7
      - cmake==3.27.4.1
      - contourpy==1.1.1
      - cycler==0.11.0
      - datasets==2.14.5
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - einops-exts==0.0.4
      - evaluate==0.4.0
      - filelock==3.12.4
      - fonttools==4.42.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - ftfy==6.1.1
      - gitdb==4.0.10
      - gitpython==3.1.36
      - gputil==1.4.0
      - huggingface-hub==0.17.1
      - idna==3.4
      - importlib-resources==6.0.1
      - inflection==0.5.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lit==16.0.6
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - more-itertools==10.1.0
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - networkx==3.1
      - nltk==3.8.1
      - numpy==1.25.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - open-clip-torch==2.20.0
      - open-flamingo==2.0.1
      - pandas==2.1.0
      - pathtools==0.1.2
      - pillow==10.0.1
      - protobuf==3.20.3
      - psutil==5.9.5
      - pyarrow==13.0.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.7
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - regex==2023.8.8
      - requests==2.31.0
      - responses==0.18.0
      - safetensors==0.3.3
      - scikit-learn==1.3.1
      - scipy==1.11.2
      - sentencepiece==0.1.98
      - sentry-sdk==1.31.0
      - setproctitle==1.3.2
      - smmap==5.0.0
      - sympy==1.12
      - threadpoolctl==3.2.0
      - timm==0.9.7
      - tokenizers==0.13.3
      - torch==2.0.1
      - torchvision==0.15.2
      - tqdm==4.66.1
      - triton==2.0.0
      - tzdata==2023.3
      - urllib3==2.0.4
      - wandb==0.15.10
      - webdataset==0.2.48
      - xxhash==3.3.0
      - yarl==1.9.2
      - zipp==3.16.2
